server:
  port: 8081

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1299
  jpa:
    hibernate:
      ddl-auto: update # "update" creates the table if it's missing
    show-sql: true     # This logs the SQL to your console so you can see if it's running
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# eureka:
#   client:
#     register-with-eureka: false
#     fetch-registry: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/